### PR TITLE
Update DSynchronize Portable to 2.34.1

### PR DESCRIPTION
**Pull request by scriptdaemon**

### CODE REVIEW

**Comment by 3D1T0R** [comment]
These (#1, #2, #3) pull requests (and associated branches) seem to be for the purpose of updating the repository to match what's currently released, yes? If so, seeing as they're already officially released, shouldn't they simply be pushed straight into the master branch?

**Comment by GordCaswell** [comment]
Pushing directly to the master branch is disabled.

**Comment by 3D1T0R** [comment]
Why? Having a pull request for each and every update, plus a merge commit for each one seems like an awful lot of noise, and fairly pointless too when you're just updating the repository to match what's already been released.
I understand that one should use a branch and pull request for things that aren't yet official, merging them once they do become official, but when you're just updating the repo to match what's already been officially released, it doesn't seem like a good way to go about things.

**Comment by GordCaswell** [comment]
Good point. I've removed the pull request requirement for this repository.

**Comment by scriptdaemon** [comment]
Moot point now, but to add: Pull requests can be squashed, omitting the merge commit. Just for future reference.

**Pull request merged**
